### ISSUE TITLE
Request: add default env vars that are useful for soft IOCs

### ISSUE THREAD

**Issue by kmpeters** [epics-modules/alive#8]
The ``STY`` environment variable is set to ``pid.screen_session_name`` when an IOC is run in screen.

The ``PROCSERV_INFO`` environment variable will hopefully be added to procServ soon (see https://github.com/ralphlange/procServ/pull/33) and will contain the PID, log & control ports for procServ.

The inclusion of ``STY`` and ``PROCSERV_INFO`` as default static environment variables will make it much easier for tools like ``iocConsole`` to automatically connect to a running soft IOC.

**Comment by dohnarms** [comment]
I added them to the defaults in alive.db.  I also made changes to the documentation.

**Comment by kmpeters** [comment]
Thanks!

Fixed by https://github.com/epics-modules/alive/commit/80583ced3946df2a755b8af895ede6a0299f071d
